---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host
summary: "Change the host port identifiers when you want to change the user label on a host port identifier, add a new host port identifier to the host, or delete a host port identifier from the host."
---
= Change the host port identifiers for a host in SANtricity System Manager
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Change the host port identifiers when you want to change the user label on a host port identifier, add a new host port identifier to the host, or delete a host port identifier from the host.

.About this task

When changing host port identifiers, keep the following guidelines in mind:

* *Add* -- When you add a host port, you are associating the host port identifier to the host you created to connect to your storage array. You can manually enter port information using a host bus adapter (HBA) utility.
* *Edit* -- You can edit the host ports to move (associate) a host port to a different host. You might have moved the host bus adapter or iSCSI initiator to a different host, so you must move (associate) the host port to the new host.
* *Delete* -- You can delete host ports to remove (unassociate) host ports from a host.

.Steps

. From the left panel, select menu:Storage[Hosts].
. Select the host to which the ports will be associated, and then click the menu:ellipsis icon[Edit Settings].
+
If you want to add ports to a host in a host cluster, expand the host cluster and select the desired host. You cannot add ports at the host cluster level.
+
An Edit host settings screen appears that shows the current host settings.

. Change the host port identifier settings as appropriate.
+
[cols="25h,~",options="header"]
|===
| Setting| Description
a|
Host Port
a|
You can choose one of the following options:

** *Add host port* -- Click *Add host port* to associate a new host port identifier to the host. The length of the host port identifier name is determined by the host interface technology. Fibre Channel and Infiniband host port identifier names must have 16 characters. iSCSI host port identifier names have a maximum of 223 characters. The port must be unique. A port number that has already been configured is not allowed.
** *Delete (X icon)* -- Click the *X* icon to remove (unassociate) a host port identifier. The delete option does not physically remove the host port. This option removes the association between the host port and the host. Unless you remove the host bus adapter or the iSCSI initiator, the host port is still recognized by the controller.
+
[NOTE]
====
If you delete a host port identifier, it is no longer associated with this host. Also, the host loses access to any of its assigned volumes through this host port identifier.
====
a|
Name
a|
If needed, you can change the port label name. The port label name must be unique. A label name that has already been configured is not allowed.
a|
CHAP Secret
a|
Appears only for iSCSI hosts. You can set or change the CHAP secret for the initiators (iSCSI hosts).

System Manager uses the Challenge Handshake Authentication Protocol (CHAP) method, which validates the identity of targets and initiators during the initial link. Authentication is based on a shared security key called a CHAP secret.
|===

. Click *Save*.
