---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group
summary: "You can change the settings for a snapshot group to change its name, auto-delete settings, the maximum number of allowed snapshot images, the percentage point at which System Manager sends a reserved capacity alert notification, or the policy to use when the reserved capacity reaches its maximum defined percentage."
---
= Change the reserved capacity settings for a snapshot group in SANtricity System Manager
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You can change the settings for a snapshot group to change its name, auto-delete settings, the maximum number of allowed snapshot images, the percentage point at which SANtricity System Manager sends a reserved capacity alert notification, or the policy to use when the reserved capacity reaches its maximum defined percentage.

During the creation of a snapshot group, reserved capacity is created to store the data for all the snapshot images contained in the group.

.Steps

. From the left panel, select menu:Storage[Pools and volume groups].
. Click the *Reserved Capacity* tab.
. Select the snapshot group that you want to edit, and then click the menu:ellipsis icon[Edit Settings].
+
The Edit snapshot group settings window appears.

. Change the settings for the snapshot group as appropriate.
+
.Field details
[%collapsible]
====

[cols="25h,~",options="header"]
|===
| Setting| Description
2+a|
*Snapshot group settings*
a|
Name
a|
The name of the snapshot group. Specifying a name for the snapshot group is required.
a|
Snapshot image auto-deletion
a|
A setting that keeps the total number of snapshot images in the group at or below a user-defined maximum. When this option is enabled, System Manager automatically deletes the oldest snapshot image in the group any time a new snapshot is created, to comply with the maximum number of snapshot images allowed for the group.
a|
Snapshot image limit
a|
A configurable value that specifies the maximum number of snapshot images allowed for a snapshot group.
2+a|
*Reserved capacity settings*
a|
Alert me when...
a|
Use the spinner box to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a snapshot group is nearing full.

When the reserved capacity for the snapshot group exceeds the specified threshold, System Manager sends an alert, allowing you time to increase reserved capacity or to delete unnecessary objects.
a|
Policy for full reserved capacity
a|
You can choose one of the following policies:

** *Purge oldest snapshot image* -- System Manager automatically purges the oldest snapshot image in the snapshot group, which releases the snapshot image reserved capacity for reuse within the group.
** *Reject writes to base volume* -- When the reserved capacity reaches its maximum defined percentage, System Manager rejects any I/O write request to the base volume that triggered the reserved capacity access.
|===
====

. Click *Save* to apply your changes to the snapshot group settings.
