---
permalink: sm-storage/change-settings-for-a-volume.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, settings, volume
summary: "You can change a volume’s settings such as its name, host assignment, segment size, modification priority, caching, and so on."
---
= Change the settings for a volume in SANtricity System Manager
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You can change a volume's settings such as its name, host assignment, segment size, modification priority, caching, and so on.

.Before you begin

The volume you want to change is in Optimal status.

NOTE: Some operations may be unavailable while changes to the volume settings are in progress

.Steps

. From the left panel, select menu:Storage[Volumes].
. Select the volume that you want to change, and then click the menu:ellipsis icon[Edit Settings].
+
The Edit Volume Settings window appears, showing the configuration settings for the selected volume.

. Configure the volume settings as needed: 
+
.Field details
[%collapsible]
====

[cols="25h,~",options="header"]
|===
| Setting| Description
a|
Name
a|
Displays the name of the volume. Change the name of a volume when the current name is no longer meaningful or applicable.
a|
Host
a|
Displays the volume assignment. You assign a volume to a host or host cluster so it can be accessed for I/O operations. This assignment grants a host or host cluster access to a particular volume or to a number of volumes in a storage array.

** *Assigned to* -- Identifies the host or host cluster that has access to the selected volume.
** *LUN* -- A logical unit number (LUN) is the number assigned to the address space that a host uses to access a volume. The volume is presented to the host as capacity in the form of a LUN. Each host has its own LUN address space. Therefore, the same LUN can be used by different hosts to access different volumes.
+
NOTE: For NVMe interfaces, this column displays Namespace ID. A namespace is NVM storage that is formatted for block access. It is analogous to a logical unit in SCSI, which relates to a volume in the storage array. The namespace ID is the NVMe controller's unique identifier for the namespace, and can be set to a value between 1 and 255. It is analogous to a logical unit number (LUN) in SCSI.

a|
Segment sizing
a|
Shows the setting for segment sizing, which appears only for volumes in a volume group. You can change the segment size to optimize performance.

*Allowed segment size transitions* -- System Manager determines the segment size transitions that are allowed. Segment sizes that are inappropriate transitions from the current segment size are unavailable on the drop-down list. Allowed transitions usually are double or half of the current segment size. For example, if the current volume segment size is 32 KiB, a new volume segment size of either 16 KiB or 64 KiB is allowed.

*SSD Cache-enabled volumes* -- You can specify a 4-KiB segment size for SSD Cache-enabled volumes. Make sure you select the 4-KiB segment size only for SSD Cache-enabled volumes that handle small-block I/O operations (for example, 16 KiB I/O block sizes or smaller). Performance might be impacted if you select 4 KiB as the segment size for SSD Cache-enabled volumes that handle large block sequential operations.

*Amount of time to change segment size* -- The amount of time to change a volume's segment size depends on these variables:

** The I/O load from the host
** The modification priority of the volume
** The number of drives in the volume group
** The number of drive channels
** The processing power of the storage array controllers
When you change the segment size for a volume, I/O performance is affected, but your data remains available.

a|
Modification priority
a|
Shows the setting for modification priority, which only appears for volumes in a volume group.

The modification priority defines how much processing time is allocated for volume modification operations relative to system performance. You can increase the volume modification priority, although this might affect system performance.

Move the slider bars to select a priority level.

*Modification priority rates* -- The lowest priority rate benefits system performance, but the modification operation takes longer. The highest priority rate benefits the modification operation, but system performance might be compromised.

|===
====

. Click *Save*.
+
System Manager changes the volume's settings based on your selections.

.After you finish

Select menu:Storage[Operations in Progress] to view the progress of the change operations that are currently running for the selected volume.
