---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume
summary: "You can change the settings for a mirrored pair volume to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a mirrored pair volume is nearing full."
---
= Change the reserved capacity settings for a mirrored pair volume in SANtricity System Manager
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You can change the settings for a mirrored pair volume to adjust the percentage point at which SANtricity System Manager sends an alert notification when the reserved capacity for a mirrored pair volume is nearing full.

.Steps

. From the left panel, select menu:Storage[Pools and volume groups].
. Select the *Reserved Capacity* tab.
. Select the mirrored pair volume that you want to edit, and then click the menu:ellipsis icon[Edit Settings].
+
The Edit Mirrored Pair Volume Reserved Capacity Settings window appears.

. Change the reserved capacity settings for the mirrored pair volume as appropriate.
+
.Field details
[%collapsible]
====

[cols="25h,~",options="header"]
|===
| Setting| Description
a|
Reserved capacity full alert threshold
a|
Use the bar to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a mirrored pair is nearing full.

When the reserved capacity for the mirrored pair exceeds the specified threshold, System Manager sends an alert, allowing you time to increase reserved capacity.


NOTE: Changing the Alert setting for one mirrored pair changes the Alert setting for all mirrored pairs that belong to the same mirror consistency group.

|===
====
. Click *Save* to apply your changes.
