---
permalink: sm-storage/how-workloads-work.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, application, workloads, volume,
summary: "When creating a volume, you select a workload to customize the storage array configuration for a specific application."
---
= How workloads work in SANtricity software
:icons: font
:imagesdir: ../media/

[.lead]
When creating a volume, you select a workload to customize the storage array configuration for a specific application.

A workload is a storage object that supports an application. You can define one or more workloads, or instances, per application. 

== Creating a workload

You must manually specify when you want to create a workload that is not associated with a specific application. You must also manually specify the volume configuration using the Add Volumes page.

== Application and workload views

To view applications and workloads, launch SANtricity System Manager. From that interface, you can view information associated with an application-specific workload in a couple of different ways:

* You can select the *Applications and workloads* tab in the Volumes page to view the storage array's volumes grouped by workload and the application type the workload is associated with.
* You can select the *Applications and workloads* tab in the Performance page to view performance metrics (latency, IOPS, and MBs) for logical objects. The objects are grouped by application and associated workload. By collecting this performance data at regular intervals, you can establish baseline measurements and analyze trends, which can help as you investigate problems related to I/O performance.
