---
permalink: sm-storage/view-performance-data-graphical.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, view, graphical, performance,
summary: "You can view graphical performance data for logical objects, physical objects, applications, and workloads."
---
= View graphical performance data in SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can view graphical performance data for logical objects, physical objects, applications, and workloads.

.About this task

The performance graphs show historical data as well as live data currently being captured. A vertical line on the graph, labeled Live updating, distinguishes historical data from live data.

*Dashboard view*

The Dashboard contains a graph showing storage array level performance. You can select limited metrics from this view, or you can click *View Performance Details* to go to menu:Monitoring[Performance] and select all the available metrics.

*Detailed view*

The graphs available from the Performance page are based on your selections:

* *Object types* -- Selects the categories of objects to include (for example, Storage array, Controllers, Pools and volume groups, Applications, Workloads, Volumes, Channels, and Drives).
* *Objects* -- Selects up to five specific objects for the selected object types.

.Steps

. Select menu:Monitoring[Performance].
. Use *Object types* and *Objects* to select the data you want to display. You can select up to five objects; use the search field in the *Objects* list to find object names or partial names.
+
Not all metrics are available for every object type. Storage arrays and controllers do not report latency, only controllers report CPU utilization, and only controllers and channels report headroom.

. Use *Time range* to select the period you want to display.
. Click *Refresh*.
. *Optional:* On an individual graph, use *Compare* to overlay another metric type for the same objects.

. As needed, use the additional options for viewing performance data.
+
.Additional options
[%collapsible]
====

[cols="25h,~" options="header"]
|===
| Option| Description
a|
Time range
a|
Select the length of time you want to view (5 minutes, 1 hour, 8 hours, 1 day, 7 days, or 30 days). The default is 1 hour.

NOTE: Loading performance data for a 30-day time range can take several minutes. Do not navigate away from the web page, refresh the web page, or close the browser while data is loading.

a|
Data point details
a|
Hover the cursor over the graph to see metrics for a particular data point.
a|
Scroll bar
a|
Use the scroll bar below the graph to view an earlier or later time span.
a|
Zoom bar
a|
Below the graph, drag the zoom bar handles to zoom out on a time span. The wider the zoom bar, the less granular the details of the graph.

To reset the graph, select one of the time frame options.
a|
Drag and drop
a|
On the graph, drag the cursor from one point in time to another to zoom in on a time span.

To reset the graph, select one of the time frame options.
|===
====
