---
permalink: sm-storage/view-and-save-performance-data-tabular.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, view, save, tabular, performance,
summary: "You can view and save performance graphs data in tabular format. This allows you to filter the data you want displayed."
---
= View and save tabular performance data in SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can view and save performance graphs data in tabular format. This allows you to filter the data you want displayed.

.Steps

. From the Performance page, click *Go to table view*.
+
A table appears that lists all the performance data for the selected objects.

. Use *Object types* and *Time range* to select the data you want to display, and then click *Refresh*.
. Click the *Show/Hide Columns* button to select the columns you want to include in the table.
+
You can click each check box to select or deselect an item.

. Select *Export to CSV* from the table menu to save the tabular view to a file of comma-separated values (CSV).
+
Depending on your browser settings, the file is either saved, or you are prompted to choose a name and location for the file.
+
The default file name format is `performanceStatistics-<storage array name>-yyyy-mm-dd_hh-mm-ss.csv`, which includes the storage array name and the date and time when the file was exported.

