---
settings:
  name: Catalyst Migration
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: Home
    url: "/index.html"
  - section: sm-hardware
  - section: sm-interface
  - section: sm-mirroring
  - section: sm-settings
  - section: sm-storage
  - section: sm-supported
  - section: um-admin
  - section: um-certificates
  - section: um-manage
