---
settings:
  name: E-Series SANtricity docs
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: Main
    url: "/index.html"
  - section: sm-interface
  - section: sm-storage
  - section: sm-mirroring
  - section: sm-hardware
  - section: sm-settings
  - section: sm-support
  - section: um-admin
  - section: um-manage
  - section: um-certificates
