---
sidebar: sidebar
permalink: whats-new.html
keywords: whats new, new features, SANtricity 12.00
summary: New features in SANtricity OS.
---
= What's new in SANtricity OS 12.00
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
The following table describes new features in SANtricity System Manager 12.0.

== New features in Version 12.10

[cols="35h,~",options="header"]
|===
|New feature |Description
a|Expanded E-Series platform support for new SANtricity System Manager user interface
a|The new user interface for SANtricity System Manager, which was introduced in the SANtricity 12.00 release for the EF80 and EF50 storage systems, has been expanded to support additional E-Series storage platforms. This means that users managing a wider range of E-Series storage systems can now benefit from the modernized interface and enhanced usability features. The expanded support includes compatibility with select models of E-Series storage systems, allowing users to take advantage of the improved navigation and streamlined management tasks across more of their storage infrastructure. 

a|SAS expansion support for EF50 and EF80 storage systems
a|The EF50 and EF80 storage systems now support SAS expansion, allowing for increased storage capacity and flexibility. With SAS expansion, you can connect additional storage enclosures to the EF50 and EF80 systems, enabling you to scale your storage environment as needed. This feature is particularly beneficial for organizations that require high-capacity storage solutions and want to maximize their investment in the EF50 and EF80 platforms.

a|NVMe over TCP support for E-Series storage systems
a|The E-Series storage systems now support NVMe over TCP, providing an additional host interface option for high-performance storage access. NVMe over TCP allows for efficient and low-latency communication between the storage system and connected hosts, leveraging the benefits of the NVMe protocol over standard TCP/IP networks. This support enhances the versatility of the E-Series systems, enabling organizations to deploy them in environments where NVMe over TCP is preferred or required.

|===

== New features in Version 12.0R1

This version contains only minor changes and no new features. For more information on the changes in this release, please refer to the E-Series SANtricity OS 12.0R1 README.

== New features in Version 12.00

This version contains only minor changes and no new features. For more information on the changes in this release, please refer to the E-Series SANtricity OS 12.0R1 README.

== New features in Version 12.0

NOTE: The SANtricity OS 12.0 release is only compatible with the new EF80 and EF50 all-flash storage systems. If you are using SANtricity OS 11.9 or older, please refer to link:known-issues.html[Known issues] for a list of new features in previous releases.

[cols="35h,~",options="header"]
|===
|New feature |Description
a|New storage system models – EF80 and EF50 all-flash storage systems
a|This release introduces the EF80 and EF50 all-NVMe-flash storage systems. The EF80 and EF50 supports 24 NVME SSD drives and a inter-controller mirroring card per controller. The supported NVMe over Fabrics host interfaces include NVMe over RoCE, NVMe over IB, NVMe over FC for EF80, and NVMe over FC for EF50. The supported SCSI interface is Fibre Channel for both systems The EF50 supports up to two host interface cards per controller while the EF80 supports up to three host interface cards per controller. 

High-capacity NVMe SSD drives of 30TB or 60TB sizes are also supported with the EF80 and EF50. The EF80 and EF50 can only utilize Dynamic Disk Pool when the array is populated with 30TB or 60TB drives.

a|New user interface for SANtricity System Manager
a|For the new EF80 and EF50 controllers, the SANtricity System Manager user interface has been redesigned to provide a more modern look and feel. The new interface includes a left-panel navigation and enhanced usability to streamline management tasks.

NOTE: The new user interface is currently available only for the EF80 and EF50 storage systems with the SANtricity 12.00 release. If you are using SANtricity 11.9 or older, please refer to link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html[SANtricity System Manager 11.9] for instructions on using the legacy user interface. 

a|Subject Alternative Names (SANs) for Server certificate now only permits Letters, digits, and hyphen characters
a|When creating or editing a Server certificate in SANtricity System Manager or Unified Manager, the Subject Alternative Names (SANs) field now only permits letters, digits, and hyphen characters. This change enhances security and ensures compatibility with industry standards for SSL/TLS certificates.

a|Dynamic Disk Pools segment size now defaults to 32K for SSD and NVMe-based systems
a|For Dynamic Disk Pools on SSD and NVMe-based systems, the default segment size has been changed to 32K. Previously, the dynamic disk pools default segment size was fixed at 128K for these systems. This change optimizes performance for workloads that involve a mix of small and large I/O operations. 

a|Script editor now available in SANtricity System Manager
a|A new script editor is now available within the SANtricity System Manager. The Script editor allows you to create or edit a script file, save a script file to the local disk of the storage management station, or load a script file from disk. The Script editor provides syntax checking and command execution capabilities for managing your storage system. For more information, see link:sm-support/use-script-editor.html[Using the Script editor^].


|===

