---
sidebar: sidebar
permalink: whats-new.html
keywords: whats new, new features, SANtricity 12.00
summary: New features in SANtricity OS.
---
= What's new in SANtricity OS 12.00
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
The following table describes new features in SANtricity System Manager 12.00.

== New features in Version 12.00

[cols="35h,~",options="header"]
|===
|New feature |Description
a|New user interface for SANtricity System Manager
a|The SANtricity System Manager user interfaces have been redesigned to provide a more modern look and feel. The new interface includes a left-panel navigation and enhanced usability to streamline management tasks.
a|DULBE support for EF300C and EF600C storage systems
a|EF300C and EF600C high-capacity flash storage systems now support the Deallocated or Unwritten Logical Block Error (DULBE) feature. This feature allows the storage system to support resource-provisioned volumes, which can improve SSD wear life and increase maximum write performance.
a|Dynamic Disk Pools segment size now defaults to 32K for SSD and NVMe-based systems
a|For Dynamic Disk Pools on SSD and NVMe-based systems, the default segment size has been changed to 32K. Previously, the dynamic disk pools default segment size was fixed at 128K for these systems. This change optimizes performance for workloads that involve a mix of small and large I/O operations.
a|Subject Alternative Names (SANs) for Server certificate now only permits Letters, digits, and hyphen characters
a|When creating or editing a Server certificate in SANtricity System Manager or Unified Manager, the Subject Alternative Names (SANs) field now only permits letters, digits, and hyphen characters. This change enhances security and ensures compatibility with industry standards for SSL/TLS certificates.

|===

