---
permalink: sm-mirroring/faq-sync-mirroring.html
sidebar: sidebar
keywords: 
summary: "This FAQ can help if you're just looking for a quick answer to a question."
---
= Sync mirroring FAQ for SANtricity System Manager
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== How does asynchronous mirroring differ from synchronous mirroring?

The Asynchronous Mirroring feature differs from the Synchronous Mirroring feature in one essential way: it captures the state of the source volume at a particular point in time and copies just the data that has changed since the last image capture.

With synchronous mirroring, the state of the primary volume is not captured at some point in time, but rather reflects all changes that were made on the primary volume to the secondary volume. The secondary volume is identical to the primary volume at every moment because, with this type of mirror, each time a write is done to the primary volume, a write is done to the secondary volume. The host does not receive an acknowledgment that the write was successful until the secondary volume is successfully updated with the changes that were made on the primary volume.

With asynchronous mirroring, the remote storage array is not fully synchronized with the local storage array, so if the application needs to transition to the remote storage array due to a loss of the local storage array, some transactions could be lost.

Comparison between mirroring features:


[cols="1a,1a" options="header"]
|===
| Asynchronous Mirroring| Synchronous Mirroring
2+a|
*Replication method*
a|
* *Point-in-Time*
+
Mirroring is done on demand or automatically according to a user-defined schedule. Schedules can be defined at the granularity of minutes. The minimum time between syncs is 10 minutes.
a|
* *Continuous*
+
Mirroring is automatically executed continuously, copying data from every host write.
2+a|
*Reserved capacity*
a|
* *Multiple*
+
A reserved capacity volume is required for each mirrored pair.
a|
* *Single*
+
Single reserved capacity volume is required for all mirrored volumes.

2+a|
*Communication*
a|
* *iSCSI and Fibre Channel*
+
Supports iSCSI and Fibre Channel interfaces between storage arrays.
a|
* *Fibre Channel*
+
Supports only Fibre Channel interfaces between storage arrays.
2+a|
*Distance*
a|
* *Unlimited*
+
Support for virtually unlimited distances between the local storage array and the remote storage array, with the distance typically limited only by the capabilities of the network and the channel extension technology.

a|

* *Restricted*
+
Typically must be within about 10 km (6.2 miles), of the local storage array to meet the latency and application performance requirements.

|===

== Synchronous mirroring - Why don't I see all my volumes?
When you are selecting a primary volume for a mirrored pair, a list shows all the eligible volumes.

Any volumes that are not eligible to be used do not display in that list. Volumes might not be eligible for any of the following reasons:

* The volume is a non-standard volume, such as a snapshot volume or thin volume.
* The volume is not optimal.
* The volume is already participating in a mirroring relationship.

== Synchronous mirroring - Why don't I see all the volumes on the remote storage array?

When you are selecting a secondary volume on the remote storage array, a list shows all the eligible volumes for that mirrored pair.

Any volumes that are not eligible to be used, do not display in that list. Volumes might not be eligible for any of the following reasons:

* The volume is a non-standard volume, such as a snapshot volume or thin volume.
* The volume is not optimal.
* The volume is already participating in a mirroring relationship.
* If you are using Data Assurance (DA), the primary volume and the secondary volume must have the same DA settings.
 ** If the primary volume is DA enabled, the secondary volume must be DA enabled.
 ** If the primary volume is not DA enabled, the secondary volume must not be DA enabled.

== Synchronous mirroring - What do I need to know before creating a mirrored pair?

You configure mirrored pairs in the SANtricity Unified Manager interface, and then manage the pairs in SANtricity System Manager.

Before creating a mirrored pair, follow these guidelines:

* You must have two storage arrays.
* Each storage array must have two controllers.
* Each controller in both the primary array and secondary array must have an Ethernet management port configured and must be connected to your network.
* Your local and remote storage arrays are connected through a Fibre Channel fabric.
* The storage arrays have a minimum firmware version of 7.84. (They can each run different OS versions.)
* You must know the password for the local and remote storage arrays.
* You must have enough free capacity on the remote storage array to create a secondary volume equal to or greater than the primary volume that you want to mirror.
* You have installed the Web Services Proxy and Unified Manager. Mirrored pairs are configured in the Unified Manager interface.
* The two storage arrays are discovered in Unified Manager.

== What impact does synchronization priority have on synchronization rates?

The synchronization priority defines how much processing time is allocated for synchronization activities relative to system performance.

The controller owner of the primary volume performs this operation in the background. At the same time, the controller owner processes local I/O writes to the primary volume and associated remote writes to the secondary volume. Because the resynchronization diverts controller processing resources from I/O activity, resynchronization can have a performance impact to the host application.

Keep these guidelines in mind to help you determine how long a synchronization priority might take and how the synchronization priorities can affect system performance.

.About synchronization priority rates
[%collapsible]
====
These priority rates are available:

* Lowest
* Low
* Medium
* High
* Highest

The lowest priority rate supports system performance, but the resynchronization takes longer. The highest priority rate supports resynchronization, but system performance might be compromised.
====
These guidelines roughly approximate the differences between the priorities.

[cols="35h,~",options="header"]
|===
| Priority rate for full synchronization| Time elapsed compared to highest synchronization rate
a|
Lowest
a|
Approximately eight times as long as at the highest priority rate.
a|
Low
a|
Approximately six times as long as at the highest priority rate.
a|
Medium
a|
Approximately three-and-a-half times as long as at the highest priority rate.
a|
High
a|
Approximately twice as long as at the highest priority rate.
|===
Volume size and host I/O rate loads affect the synchronization time comparisons.

== Why is it recommended to use a manual synchronization policy?

Manual resynchronization is recommended because it lets you manage the resynchronization process in a way that provides the best opportunity for recovering data.

If you use an Automatic resynchronization policy and intermittent communication problems occur during resynchronization, data on the secondary volume could be temporarily corrupted. When resynchronization is complete, the data is corrected.
