---
permalink: sm-interface/home-page.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, home page
summary: "The Dashboard provides a summary view for the daily management of your storage array. When you log into System Manager, the Dashboard is the first screen displayed."
---
= Learn about the SANtricity System Manager Dashboard
:icons: font
:imagesdir: ../media/

[.lead]
The Dashboard provides a summary view for the daily management of your storage array. When you log into SANtricity System Manager, the Dashboard is the first screen displayed.

The dashboard view comprises three summary areas that contain key information about the state and health of your storage array. You can find more information from the summary area.

* *Performance*
+
The Performance area allows you to compare and contrast resource usage over time. You can view a storage array's performance metrics for response time (IOPS), transfer rates (MiB/s), and the amount of processing capacity being used (CPU).

* *Capacity*
+
The Capacity area displays a chart view of the allocated capacity, free storage capacity, and unassigned storage capacity in your storage array.

* *Storage Hierarchy*
+
The Storage Hierarchy area provides an organized view of the various hardware components and storage objects managed by your storage array. Click the drop-down arrow to perform a certain action on that hardware component or storage object.
