---
permalink: sm-hardware/turn-on-drive-locator-light.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, turn, drive, locator, light, LEDs
summary: "From the Hardware page, you can turn on the locator light to find the physical location of a drive in the storage array."
---
= Turn on a drive locator light in SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
From the Hardware page, you can turn on the locator light to find the physical location of a drive in the storage array.

.About this task

You can locate single drives or multiple drives shown on the Hardware page.

.Steps

. From the left panel, select menu:Hardware[Drives].
. To locate one or more drives, do one of the following:
  ** *Single drive* -- From the shelf graphic, find the drive you want to physically locate in the array. Click the drive to display its context menu, and then select *Turn on locator light*.
+
The drive's locator light turns on. When you have physically located the drive, return to the dialog and select *Turn off*.

 ** *Multiple drives* -- In the filter field, select a physical drive type and a logical drive type. The number of drives matching your criteria is shown on the far right of the field. Next, click *turn on locator lights*. When you have physically located the drives, return to the dialog and select *Turn off*.
