---
permalink: sm-hardware/update-battery-learn-cycles.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, update, battery, learn, cycles
summary: "A learn cycle is an automatic cycle for calibrating the smart battery gauge. The cycles are scheduled to start automatically, at the same day and time, in 8-week intervals (per controller). If you want to set a different schedule, you can adjust the learn cycles."
---
= Update battery learn cycles in SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
A learn cycle is an automatic cycle for calibrating the smart battery gauge. The cycles are scheduled to start automatically, at the same day and time, in 8-week intervals (per controller). If you want to set a different schedule, you can adjust the learn cycles.

.About this task

Updating the learn cycles affect both controller batteries.

.Steps

. From the left panel, select *Hardware*.
. If the graphic shows the drives, click the *Controllers & Components* tab.
+
The graphic changes to show the controllers instead of the drives.
. Select the drop-down list for the Controller Shelf, and then select *View settings*.
. Select the *Batteries* tab.
. Select *Update battery learn cycles*.
+
The Update Battery Learn Cycles dialog box opens.

. From the drop-down lists, select a new day and time.
. Click *Save*.
