---
permalink: sm-hardware/view-controller-settings.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, view, controller, settings
summary: "You can view information about a controller, such as the status of the host interfaces, drive interfaces, and management ports."
---
= View controller settings in SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can view information about a controller, such as the status of the host interfaces, drive interfaces, and management ports.

.Steps

. From the left panel, select menu:Hardware[Controllers and components].
. Do one of the following actions to display the controller settings:
 ** Click the controller to display the context menu, and then select *View settings*.
 ** Select the controller icon (next to the *Shelf* drop-down list). For duplex configurations, select either *Controller A* or *Controller B* from the dialog box, and then click *Next*.
+
The Controller settings sliding menu opens.
. Review the sections to move between controller property settings.
+
.Field details
[%collapsible]
====

[cols="25h,~",options="header"]
|===
| Section| Description
a|
Details
a|
Shows the controller status, date/time, model name, and replacement part number.
a|
Current configuration
a|
Shows the current firmware version and NVRAM version.
a|
Data cache
a|
Shows data cache totals.
a|
Data cache modules
a|
Shows cache module location, status, and capacity.
a|
Processor cache
a|
Shows processor cache totals.
a|
Cache backup devices
a|
Shows cache backup device location, status, and capacity.
a|
Host interfaces
a|
Shows host interface information and link status for each port.
a|
Drive interfaces
a|
Shows drive interface information and link status for each port.
a|
Management port settings
a|
Shows management port details, including controller hostname, remote login, and IP network settings.
a|
Domain name system (DNS) server settings
a|
Shows DNS configuration, primary DNS server, and backup DNS server.
a|
Network time protocol (NTP) server settings
a|
Shows NTP service and NTP server configuration details.
|===
====

. Click *Close*.
